---
- hosts: webserver
  vars:
    app_name: "{{ app_name }}"
  tasks:
    - name: Make sure that we can connect to the machine
      ping:

    - name: enable war
      command: /home/kvidya/karthik/wildfly-9.0.1.Final/bin/jboss-cli.sh --connect "deploy --name="{{ app_name }}""






